export const files = [
  {
    id: 'sitomnia',
    title: 'Sitomnia',
    date: '06.2025',
    cover: new URL('./../assets/covers/sitomnia.png', import.meta.url).href,
    description: `Sitomnia is an application designed to help older adults organize their daily lives. It provides a note-taking tool and a calendar, both tailored to their specific habits and needs. The app also features an AI-powered conversational agent specifically adapted for this demographic, enabling users to ask questions and receive simple, accessible assistance.\n
      Sitomnia was developed using a co-design approach as part of a thesis on participatory design methods. End users were involved throughout the development cycle, ensuring the creation of an application truly suited to their expectations, usage patterns, and needs.`,
    link: 'https://sitomnia.valentinluginbuhl.fr',
    wiki: 'https://github.com/lelinguine/sitomnia-project/wiki',
    github: 'https://github.com/lelinguine/sitomnia-project',
    figma: 'https://www.figma.com/community/file/1522331991896573429',
  },
  {
    id: 'bernalis',
    title: 'Bernalis',
    date: '05.2025',
    cover: new URL('./../assets/covers/bernalis.png', import.meta.url).href,
    description: `TODO`,
    link: 'https://www.figma.com/proto/uAJFoIITJLfz5WiYJgg5tr/Bernalis?node-id=64-131&p=f&t=3ckZYj7hMAar5GvT-1&scaling=scale-down&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=1%3A16',
    figma: 'https://www.figma.com/community/file/1507827698115770120',
  },
  {
    id: 'othello',
    title: 'Othello',
    date: '02.2025',
    cover: new URL('./../assets/covers/othello.png', import.meta.url).href,
    description: `TODO`,
    link: 'https://othello.valentinluginbuhl.fr',
  },
  {
    id: 'brainine',
    title: 'Brainine',
    date: '02.2023',
    cover: new URL('./../assets/covers/brainine.png', import.meta.url).href,
    description: `TODO`,
    link: 'https://www.figma.com/proto/HE3G74FrhRfSImeeC4eCCH/Brainine?node-id=2-757&p=f&viewport=989%2C460%2C0.16&t=ApR0uE5dZvFCHAKP-1&scaling=scale-down&content-scaling=fixed&starting-point-node-id=2%3A819&page-id=0%3A1',
    figma: 'https://www.figma.com/community/file/1308490173999723476',
  },
  {
    id: 'supervision',
    title: 'Supervision',
    date: '06.2022',
    cover: new URL('./../assets/covers/supervision.png', import.meta.url).href,
    description: `TODO`,
    link: 'https://supervision.valentinluginbuhl.fr',
    github: 'https://github.com/lelinguine/supervision-project',
  },
]
